# Generated by Django 5.1.4 on 2024-12-24 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='colony',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='book', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
