# Generated by Django 5.1.4 on 2024-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_desc_alter_book_edition_alter_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
