# Generated by Django 5.1.4 on 2024-12-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_edition_alter_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(default='*', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(default='*', max_length=100, null=True),
        ),
    ]
