# Generated by Django 5.1.4 on 2024-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_edition_alter_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(default='Add Description', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(default='Write Edition of Book', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(default='Write Publication', max_length=100),
        ),
    ]
