# Generated by Django 5.1.4 on 2024-12-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_author_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
