# Generated by Django 5.1.4 on 2024-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='colony',
        ),
    ]
