# Generated by Django 5.1.4 on 2024-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
