# Generated by Django 5.1.4 on 2024-12-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_photo_book_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.JSONField(default=[]),
        ),
    ]
