# Generated by Django 5.1.4 on 2024-12-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
    ]
