# Generated by Django 5.1.4 on 2024-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_imagemodel_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='books'),
        ),
    ]
