# Generated by Django 5.1.4 on 2024-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_imagemodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
