# Generated by Django 5.1.4 on 2024-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='cart', to='books.book'),
        ),
    ]
