# Generated by Django 5.1.4 on 2024-12-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_remove_cart_books_cart_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
