# Generated by Django 5.1.4 on 2025-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_alter_cart_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
        migrations.RemoveField(
            model_name='book',
            name='state',
        ),
        migrations.AddField(
            model_name='book',
            name='selected_address_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
