# Generated by Django 5.1.4 on 2025-01-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_remove_book_city_remove_book_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='selected_address_id',
            field=models.IntegerField(),
        ),
    ]
