# Generated by Django 5.1.4 on 2025-01-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_alter_book_selected_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
