# Generated by Django 5.1.4 on 2025-01-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
