# Generated by Django 5.1.4 on 2025-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
