# Generated by Django 5.1.4 on 2024-12-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dilevery_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
