# Generated by Django 5.1.4 on 2024-12-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='complete_address',
            new_name='full_address',
        ),
    ]
