# Generated by Django 5.1.4 on 2024-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_complete_address_addresses_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='some_instructions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='full_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
