# Generated by Django 5.1.4 on 2024-12-31 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_addresses_some_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_no', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('full_address', models.CharField(max_length=200)),
                ('some_instructions', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
