# Generated by Django 5.1.4 on 2024-12-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address_delete_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_no',
        ),
    ]
