# Generated by Django 5.1.4 on 2025-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_address_address_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
