# Generated by Django 5.1.4 on 2025-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_address_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='multiavatar_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
